import { PrismaClient } from '@prisma/client';

export async function seedCities(prisma: PrismaClient) {
  console.log('Seeding cities...');

  // Extract cities from the comprehensive list
  // Source: https://ontheworldmap.com/all/cities/
  const cities = [
    // Major US Cities
    'New York',
    'Los Angeles',
    'Chicago',
    'Houston',
    'Phoenix',
    'Philadelphia',
    'San Antonio',
    'San Diego',
    'Dallas',
    'San Jose',
    'Austin',
    'Jacksonville',
    'San Francisco',
    'Columbus',
    'Fort Worth',
    'Charlotte',
    'Seattle',
    'Denver',
    'Washington',
    'Boston',
    'El Paso',
    'Nashville',
    'Detroit',
    'Oklahoma City',
    'Portland',
    'Las Vegas',
    'Memphis',
    'Louisville',
    'Baltimore',
    'Milwaukee',
    'Albuquerque',
    'Tucson',
    'Fresno',
    'Sacramento',
    'Kansas City',
    'Mesa',
    'Atlanta',
    'Omaha',
    'Colorado Springs',
    'Raleigh',
    'Miami',
    'Long Beach',
    'Virginia Beach',
    'Oakland',
    'Minneapolis',
    'Tulsa',
    'Arlington',
    'Tampa',
    'New Orleans',
    'Wichita',
    'Cleveland',
    'Bakersfield',
    'Aurora',
    'Honolulu',
    'Anaheim',
    'Santa Ana',
    'Riverside',
    'Corpus Christi',
    'Lexington',
    'Henderson',
    'Stockton',
    'Saint Paul',
    'St. Louis',
    'Cincinnati',
    'St. Petersburg',
    'Pittsburgh',
    'Greensboro',
    'Lincoln',
    'Anchorage',
    'Plano',
    'Orlando',
    'Irvine',
    'Newark',
    'Durham',
    'Chula Vista',
    'Toledo',
    'Fort Wayne',
    'St. Louis',
    'Chandler',
    'Laredo',
    'Norfolk',
    'Madison',
    'Durham',
    'Lubbock',
    'Buffalo',
    'Jersey City',
    'Chandler',
    'Scottsdale',
    'Glendale',
    'Reno',
    'Winston-Salem',
    'North Las Vegas',
    'Gilbert',
    'Chesapeake',
    'Birmingham',
    'Fremont',
    'Richmond',
    'Boise',
    'San Bernardino',
    'Spokane',
    'Baton Rouge',
    'Des Moines',
    'Modesto',
    'Rochester',
    'Tacoma',
    'Fontana',
    'Oxnard',
    'Moreno Valley',
    'Fayetteville',
    'Yonkers',
    'Huntington Beach',
    'Glendale',
    'Santa Clarita',
    'Grand Rapids',
    'Amarillo',
    'Port St. Lucie',
    'Huntsville',
    'Grand Prairie',
    'Brownsville',
    'Overland Park',
    'Santa Clarita',
    'Providence',
    'Garden Grove',
    'Chattanooga',
    'Oceanside',
    'Jackson',
    'Fort Lauderdale',
    'Santa Rosa',
    'Rancho Cucamonga',
    'Portland',
    'Ontario',
    'Vancouver',
    'Sioux Falls',
    'Peoria',
    'Oxnard',
    'Aurora',
    'Rockford',
    'Elk Grove',
    'Salem',
    'Corona',
    'Pembroke Pines',
    'Eugene',
    'Fort Collins',
    'Cary',
    'Santa Ana',
    'Springfield',
    'Lancaster',
    'Salinas',
    'Palmdale',
    'Hayward',
    'Pomona',
    'Alexandria',
    'Lakewood',
    'Sunnyvale',
    'Hollywood',
    'Torrance',
    'Naperville',
    'Escondido',
    'Kansas City',
    'Joliet',
    'Bridgeport',
    'Savannah',
    'Paterson',
    'McAllen',
    'Syracuse',
    'Pasadena',
    'Mesquite',
    'Dayton',
    'Fullerton',
    'Orange',
    'Olathe',
    'Thornton',
    'Miramar',
    'Denton',
    'Roseville',
    'Carrollton',
    'Waco',
    'Surprise',
    'Sterling Heights',
    'Vallejo',
    'Pasadena',
    'Victorville',
    'Allentown',
    'Abilene',
    'Norman',
    'Beaumont',
    'Independence',
    'Evansville',
    'Odessa',
    'Frisco',
    'Ann Arbor',
    'Athens',
    'Round Rock',
    'Thousand Oaks',
    'Topeka',
    'Simi Valley',
    'Fargo',
    'Concord',
    'Lakeland',
    'Clovis',
    'Columbia',
    'El Monte',
    'Abilene',
    'Lansing',
    'Downey',
    'Westminster',
    'Berkeley',
    'Midland',
    'Carlsbad',
    'Richardson',
    'Arvada',
    'Richmond',
    'Fairfield',
    'Inglewood',
    'Broken Arrow',
    'Miami Gardens',
    'Burbank',
    'Rochester',
    'Gresham',
    'Daly City',
    'Lewisville',
    'Tempe',
    'South Bend',
    'Elgin',
    'West Covina',
    'Clearwater',
    'Waterbury',
    'Santa Clara',
    'Provo',
    'West Jordan',
    'Gainesville',
    'Antioch',
    'Cambridge',
    'Edinburg',
    'Lowell',
    'Pueblo',
    'Lafayette',
    'Lakeland',
    'Wilmington',
    'Arlington',
    'Ventura',
    'Everett',
    'Davenport',
    'Rialto',
    'Tuscaloosa',
    'Centennial',
    'Murfreesboro',
    'High Point',
    'Billings',
    'Richmond',
    'Killeen',
    'Sandy Springs',
    'Jurupa Valley',
    'Hialeah',
    'Allen',
    'Rio Rancho',
    'Yuma',
    'Spokane Valley',
    'Santa Monica',
    'Kenosha',
    'El Cajon',
    'Renton',
    'Davenport',
    'South Gate',
    'Brockton',
    'Las Cruces',
    'Compton',
    'Tyler',
    'Nampa',
    'Avondale',
    'Bend',
    'Fayetteville',
    'San Mateo',
    'Hesperia',
    'Green Bay',
    'Westminster',
    'Santa Barbara',
    'Boca Raton',
    'Albany',
    'Norwalk',
    'San Angelo',
    'Racine',
    'Murrieta',
    'Temecula',
    'Sparks',
    'Bellingham',
    'Lakewood',
    'Gary',
    'Mission Viejo',
    'Roswell',
    'Lynn',
    'Redding',
    'Yakima',
    'Turlock',
    'Greenville',
    'St. George',
    'Boulder',
    'Kennewick',
    'Fall River',
    'Largo',
    'Thousand Oaks',
    'Santa Monica',
    'El Centro',
    'Oshkosh',
    'San Leandro',
    'Appleton',
    'Chico',
    'Newton',
    'Manteca',
    'San Marcos',
    'Concord',
    'Hammond',
    'Fargo',
    'Lodi',
    'Carmel',
    'Bismarck',
    'San Rafael',
    'Woodland',
    'Palo Alto',
    'Redwood City',
    'Yuba City',
    'Madera',
    'Santa Cruz',
    'Eureka',
    'Davis',
    'Capitola',
    'Monterey',
    'Salinas',
    'Watsonville',
    'Hollister',
    // Major International Cities
    'London',
    'Paris',
    'Tokyo',
    'Sydney',
    'Melbourne',
    'Toronto',
    'Vancouver',
    'Montreal',
    'Calgary',
    'Edmonton',
    'Mexico City',
    'Guadalajara',
    'Monterrey',
    'Buenos Aires',
    'São Paulo',
    'Rio de Janeiro',
    'Brasília',
    'Lima',
    'Bogotá',
    'Santiago',
    'Madrid',
    'Barcelona',
    'Rome',
    'Milan',
    'Naples',
    'Venice',
    'Florence',
    'Berlin',
    'Munich',
    'Hamburg',
    'Frankfurt',
    'Cologne',
    'Amsterdam',
    'Rotterdam',
    'Brussels',
    'Vienna',
    'Zurich',
    'Geneva',
    'Stockholm',
    'Oslo',
    'Copenhagen',
    'Helsinki',
    'Dublin',
    'Edinburgh',
    'Glasgow',
    'Manchester',
    'Liverpool',
    'Birmingham',
    'Leeds',
    'Bristol',
    'Lisbon',
    'Porto',
    'Athens',
    'Thessaloniki',
    'Istanbul',
    'Ankara',
    'Dubai',
    'Abu Dhabi',
    'Doha',
    'Riyadh',
    'Jeddah',
    'Cairo',
    'Alexandria',
    'Casablanca',
    'Lagos',
    'Nairobi',
    'Johannesburg',
    'Cape Town',
    'Mumbai',
    'Delhi',
    'Bangalore',
    'Hyderabad',
    'Chennai',
    'Kolkata',
    'Pune',
    'Ahmedabad',
    'Jaipur',
    'Surat',
    'Lucknow',
    'Kanpur',
    'Beijing',
    'Shanghai',
    'Guangzhou',
    'Shenzhen',
    'Chengdu',
    'Chongqing',
    'Hangzhou',
    'Wuhan',
    "Xi'an",
    'Nanjing',
    'Hong Kong',
    'Singapore',
    'Bangkok',
    'Jakarta',
    'Manila',
    'Ho Chi Minh City',
    'Hanoi',
    'Seoul',
    'Busan',
    'Taipei',
    'Kuala Lumpur',
    'Phnom Penh',
    'Vientiane',
    'Yangon',
    'Dhaka',
    'Kathmandu',
    'Colombo',
    'Karachi',
    'Lahore',
    'Islamabad',
    'Tehran',
    'Baghdad',
    'Damascus',
    'Beirut',
    'Amman',
    'Jerusalem',
    'Tel Aviv',
    'Haifa',
    'Nicosia',
    'Limassol',
    'Sydney',
    'Melbourne',
    'Brisbane',
    'Perth',
    'Adelaide',
    'Gold Coast',
    'Newcastle',
    'Canberra',
    'Sunshine Coast',
    'Wollongong',
    'Auckland',
    'Wellington',
    'Christchurch',
    'Hamilton',
    'Tauranga',
    'Napier',
    'Palmerston North',
    'Rotorua',
    'New Plymouth',
    'Invercargill',
    'Tokyo',
    'Yokohama',
    'Osaka',
    'Nagoya',
    'Sapporo',
    'Fukuoka',
    'Kobe',
    'Kawasaki',
    'Kyoto',
    'Saitama',
    'Hiroshima',
    'Sendai',
    'Chiba',
    'Kitakyushu',
    'Sakai',
    'Niigata',
    'Hamamatsu',
    'Shizuoka',
    'Okayama',
    'Kumamoto',
    'Kagoshima',
    'Hachioji',
    'Utsunomiya',
    'Matsuyama',
    'Kanazawa',
    'Nagano',
    'Oita',
    'Fukushima',
    'Akita',
    'Aomori',
    'Moscow',
    'Saint Petersburg',
    'Novosibirsk',
    'Yekaterinburg',
    'Kazan',
    'Nizhny Novgorod',
    'Chelyabinsk',
    'Samara',
    'Omsk',
    'Rostov-on-Don',
    'Ufa',
    'Krasnoyarsk',
    'Voronezh',
    'Perm',
    'Volgograd',
    'Krasnodar',
    'Saratov',
    'Tyumen',
    'Tolyatti',
    'Izhevsk',
    'Barnaul',
    'Ulyanovsk',
    'Irkutsk',
    'Khabarovsk',
    'Yaroslavl',
    'Vladivostok',
    'Makhachkala',
    'Tomsk',
    'Orenburg',
    'Kemerovo',
    'Novokuznetsk',
    'Ryazan',
    'Astrakhan',
    'Naberezhnye Chelny',
    'Penza',
    'Lipetsk',
    'Kirov',
    'Cheboksary',
    'Kaliningrad',
    'Tula',
  ];

  // Map of known coordinates for major cities
  const CITY_COORDINATES: Record<string, { lat: number; lng: number }> = {
    'New York': { lat: 40.7128, lng: -74.006 },
    'Los Angeles': { lat: 34.0522, lng: -118.2437 },
    Chicago: { lat: 41.8818, lng: -87.6232 },
    'San Francisco': { lat: 37.7749, lng: -122.4194 },
    Seattle: { lat: 47.6062, lng: -122.3321 },
    Austin: { lat: 30.2672, lng: -97.7431 },
    Boston: { lat: 42.3601, lng: -71.0589 },
    Miami: { lat: 25.7617, lng: -80.1918 },
    'Palo Alto': { lat: 37.4419, lng: -122.143 },
    'San Jose': { lat: 37.3382, lng: -121.8863 },
    Cambridge: { lat: 42.3736, lng: -71.1097 },
    Brooklyn: { lat: 40.6782, lng: -73.9442 },
    Manhattan: { lat: 40.7831, lng: -73.9712 },
    'Santa Monica': { lat: 34.0195, lng: -118.4912 },
    Hollywood: { lat: 34.0928, lng: -118.3287 },
    Bellevue: { lat: 47.6101, lng: -122.2015 },
    'New Haven': { lat: 41.3083, lng: -72.9279 },
    Princeton: { lat: 40.3573, lng: -74.6672 },
    Philadelphia: { lat: 39.9526, lng: -75.1652 },
    Durham: { lat: 35.994, lng: -78.8986 },
    Evanston: { lat: 42.0451, lng: -87.6877 },
    Ithaca: { lat: 42.444, lng: -76.5019 },
    London: { lat: 51.5074, lng: -0.1278 },
    Paris: { lat: 48.8566, lng: 2.3522 },
    Tokyo: { lat: 35.6762, lng: 139.6503 },
    Toronto: { lat: 43.65107, lng: -79.347015 },
    Sydney: { lat: -33.8688, lng: 151.2093 },
  };

  let seededCount = 0;
  for (const cityName of cities) {
    try {
      const coords = CITY_COORDINATES[cityName] || { lat: null, lng: null };

      await prisma.city.upsert({
        where: { name: cityName },
        update: {
          latitude: coords.lat,
          longitude: coords.lng,
        },
        create: {
          name: cityName,
          latitude: coords.lat,
          longitude: coords.lng,
        },
      });
      seededCount++;
    } catch (error) {
      console.error(`Error seeding city ${cityName}:`, error);
    }
  }
  console.log(`Seeded ${seededCount} cities`);
}
